In [1]:
import torch
import numpy as np
from luwiji.neural_network import illustration, demo

In [2]:
torch.__version__

'1.7.0'

# Sample data

In [3]:
data = demo.example_data_1
data

array([[[241, 213,  36, 138,  35],
        [236, 231, 243, 123,  57],
        [ 36, 123,  24, 212,  25],
        [ 65, 152, 191,  35, 206],
        [127, 243, 164,  31,  19]],

       [[ 26,  61, 236, 154,  19],
        [ 30, 140,  65, 230, 239],
        [ 45,   9, 199, 180, 100],
        [158, 160, 198, 192, 112],
        [ 45, 133,  97, 246, 124]],

       [[ 69, 124, 197, 121, 161],
        [ 65, 181,   5,  61,  47],
        [100,  96, 245, 217,  81],
        [ 39, 146,  60, 188,  77],
        [153,   6, 136, 193, 234]]])

### Mengubah numpy array menjadi tensor

In [4]:
data_tensor = torch.tensor(data)
data_tensor

tensor([[[241, 213,  36, 138,  35],
         [236, 231, 243, 123,  57],
         [ 36, 123,  24, 212,  25],
         [ 65, 152, 191,  35, 206],
         [127, 243, 164,  31,  19]],

        [[ 26,  61, 236, 154,  19],
         [ 30, 140,  65, 230, 239],
         [ 45,   9, 199, 180, 100],
         [158, 160, 198, 192, 112],
         [ 45, 133,  97, 246, 124]],

        [[ 69, 124, 197, 121, 161],
         [ 65, 181,   5,  61,  47],
         [100,  96, 245, 217,  81],
         [ 39, 146,  60, 188,  77],
         [153,   6, 136, 193, 234]]], dtype=torch.int32)

### mengubah kembali tensor menjadi numpy array

In [5]:
data_tensor.numpy()

array([[[241, 213,  36, 138,  35],
        [236, 231, 243, 123,  57],
        [ 36, 123,  24, 212,  25],
        [ 65, 152, 191,  35, 206],
        [127, 243, 164,  31,  19]],

       [[ 26,  61, 236, 154,  19],
        [ 30, 140,  65, 230, 239],
        [ 45,   9, 199, 180, 100],
        [158, 160, 198, 192, 112],
        [ 45, 133,  97, 246, 124]],

       [[ 69, 124, 197, 121, 161],
        [ 65, 181,   5,  61,  47],
        [100,  96, 245, 217,  81],
        [ 39, 146,  60, 188,  77],
        [153,   6, 136, 193, 234]]])

###  Cek ukuran dari tensor

In [6]:
data_tensor.shape

torch.Size([3, 5, 5])

tensor orde 3 dengan ukuran 5x5

### Format tensor pada pytorch harus NCHW

`N` untuk Banyak data, `C` untuk chanel/ orde tensor, `H` untuk height dan `W` untuk width

In [7]:
data_tensor = data_tensor.view(1,3,5,5)
data_tensor

tensor([[[[241, 213,  36, 138,  35],
          [236, 231, 243, 123,  57],
          [ 36, 123,  24, 212,  25],
          [ 65, 152, 191,  35, 206],
          [127, 243, 164,  31,  19]],

         [[ 26,  61, 236, 154,  19],
          [ 30, 140,  65, 230, 239],
          [ 45,   9, 199, 180, 100],
          [158, 160, 198, 192, 112],
          [ 45, 133,  97, 246, 124]],

         [[ 69, 124, 197, 121, 161],
          [ 65, 181,   5,  61,  47],
          [100,  96, 245, 217,  81],
          [ 39, 146,  60, 188,  77],
          [153,   6, 136, 193, 234]]]], dtype=torch.int32)

In [8]:
data_tensor.shape

torch.Size([1, 3, 5, 5])

### Konversi tensor ke list biasa

In [9]:
data_list = data_tensor.tolist()
data_list

[[[[241, 213, 36, 138, 35],
   [236, 231, 243, 123, 57],
   [36, 123, 24, 212, 25],
   [65, 152, 191, 35, 206],
   [127, 243, 164, 31, 19]],
  [[26, 61, 236, 154, 19],
   [30, 140, 65, 230, 239],
   [45, 9, 199, 180, 100],
   [158, 160, 198, 192, 112],
   [45, 133, 97, 246, 124]],
  [[69, 124, 197, 121, 161],
   [65, 181, 5, 61, 47],
   [100, 96, 245, 217, 81],
   [39, 146, 60, 188, 77],
   [153, 6, 136, 193, 234]]]]

In [10]:
tensor_skalar = torch.tensor(10)
tensor_skalar

tensor(10)

In [11]:
tensor_skalar.item()

10

### CPU dan GPU

In [12]:
data_tensor.cpu()

tensor([[[[241, 213,  36, 138,  35],
          [236, 231, 243, 123,  57],
          [ 36, 123,  24, 212,  25],
          [ 65, 152, 191,  35, 206],
          [127, 243, 164,  31,  19]],

         [[ 26,  61, 236, 154,  19],
          [ 30, 140,  65, 230, 239],
          [ 45,   9, 199, 180, 100],
          [158, 160, 198, 192, 112],
          [ 45, 133,  97, 246, 124]],

         [[ 69, 124, 197, 121, 161],
          [ 65, 181,   5,  61,  47],
          [100,  96, 245, 217,  81],
          [ 39, 146,  60, 188,  77],
          [153,   6, 136, 193, 234]]]], dtype=torch.int32)

In [13]:
data_tensor.cuda()

tensor([[[[241, 213,  36, 138,  35],
          [236, 231, 243, 123,  57],
          [ 36, 123,  24, 212,  25],
          [ 65, 152, 191,  35, 206],
          [127, 243, 164,  31,  19]],

         [[ 26,  61, 236, 154,  19],
          [ 30, 140,  65, 230, 239],
          [ 45,   9, 199, 180, 100],
          [158, 160, 198, 192, 112],
          [ 45, 133,  97, 246, 124]],

         [[ 69, 124, 197, 121, 161],
          [ 65, 181,   5,  61,  47],
          [100,  96, 245, 217,  81],
          [ 39, 146,  60, 188,  77],
          [153,   6, 136, 193, 234]]]], device='cuda:0', dtype=torch.int32)

# Mengatur tipe data tensor

###  integer (bilangan bulat)

In [16]:
torch.LongTensor(data)

tensor([[[241, 213,  36, 138,  35],
         [236, 231, 243, 123,  57],
         [ 36, 123,  24, 212,  25],
         [ 65, 152, 191,  35, 206],
         [127, 243, 164,  31,  19]],

        [[ 26,  61, 236, 154,  19],
         [ 30, 140,  65, 230, 239],
         [ 45,   9, 199, 180, 100],
         [158, 160, 198, 192, 112],
         [ 45, 133,  97, 246, 124]],

        [[ 69, 124, 197, 121, 161],
         [ 65, 181,   5,  61,  47],
         [100,  96, 245, 217,  81],
         [ 39, 146,  60, 188,  77],
         [153,   6, 136, 193, 234]]])

### Float

In [17]:
torch.FloatTensor(data)

tensor([[[241., 213.,  36., 138.,  35.],
         [236., 231., 243., 123.,  57.],
         [ 36., 123.,  24., 212.,  25.],
         [ 65., 152., 191.,  35., 206.],
         [127., 243., 164.,  31.,  19.]],

        [[ 26.,  61., 236., 154.,  19.],
         [ 30., 140.,  65., 230., 239.],
         [ 45.,   9., 199., 180., 100.],
         [158., 160., 198., 192., 112.],
         [ 45., 133.,  97., 246., 124.]],

        [[ 69., 124., 197., 121., 161.],
         [ 65., 181.,   5.,  61.,  47.],
         [100.,  96., 245., 217.,  81.],
         [ 39., 146.,  60., 188.,  77.],
         [153.,   6., 136., 193., 234.]]])